language: node_js
node_js:
- '8'
install:
- npm install
- npm install -g gulp-cli
script: npm run build
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: AKIAIG3WBSRYDYBODKAA
  region: ap-northeast-2
  app: truenestweb
  env: truenestweb-env
  bucket_name: elasticbeanstalk-ap-northeast-2-748321859832
after_deploy: npm start
env:
  global:
    secure: ycDy5hpk1aXfG/JwW4MwF3XonlBt6r7qxZtkYXv6gtamqCDyJkGOkUUhtOl30FI19qUO6FAtrijLfgFwg5Ds7X65kAfrwKAglyMJjgFC4SiLUISq1AgKeGvx0X3QyYyIoP9QNnaFz0DnHIzWYKL1kABatk16kEUj0tHuxzIGVeJJbwhNLlNDeAmpW2o7H9YxcGqYey6KaTVV3X91y1upK/s96Bd2IasacYW7LOMn8fu7ddNFycRyI+qT66tOUWYbcQQ5NzACvyuC49DUwMzpRaNSIjbdSTvMwvh+98+yWsXM0fmLjebydvcj6E0aauDQeoohMaMqQwYNeiJ8Jmfy4CQg1dCWchlved35FX2Ms7r6Ayk/QmT3YDadzK7ujODp+JDiWIZUi1L7cWDSj7HuHvyFxtwNjgusRk3QYwFBloTaJhoLioSZrc4nQKokF4x8aSEb8HpB81H8IXjPpdIdYvJ12iiU5lPY0iYSzrnrzwOPU17ZreNuqV6HFPjd5t72dZV0au/xWB24RRxvbWg5Ns5upUxfoUbghfW4FEIiRtefnEOAIY49hsME0ykDHRPt87sRIOc5jmaw0Yc0bJlamdWUotGgY+z5+1F8jFWn/l58e7RPa8WM769ffzjQrjgCTtVOE1hKPBrp5mdJKSbtsBMz/ZOOUNns8TkjNxRQXK8=
