language: node_js
node_js:
- '8'
install:
- npm install
- npm install -g gulp-cli
script: npm run build
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: AKIAIU5T35CNLQZXZFMA
  secret_access_key:
    secure: UVhOWIlY/Vu6ASLCTv6Nzp798gz6pK53Whl57fqz0lauJuMniZYN5WKx1ErEeD2P3edfJSgm7yU7I5Kliyfmpb4zR618Xh0k9DBXxPlWFgDqd6WUg0dYB0xl/ABBXlkTlUmN2aV6wzMfp9ZH1HRa9NyFxzhZt55/fkol9ceTpgvKKbbh+IXt42FWwilIharcD9dUUlLx7JTeKoAQr0j8VDY6y7XWauXKi3y/DOFv88GjBqzrk2RmZagowmILvuonwFVFj303TGQEIk8HGm3Nt8yQtDDWLESCF60UewrtEGaT62L9nDngeNkP2lUP6DPP3KCl3U8ujth5EG2x5TLJr+7a6Z+DA9qAGyZ+zAhDatx7zw9jrkKe8Hfwmtej/y5TGM/xCygV2OyZlu1/1Nrwlg7ryy9bUrILMQIly16Wm9IrPji5g1xNWGRP4d+/L+RXJddP6EgpgAK1KFHDCHO8zmrCHP+/uyFH7dZ587OQYDvRm7Q84JL1dLayPX4ngUNyqvGJxec9sPg1ZmliA+G0ReNjbQiQktIUOVPAVVOTqZ91M9DLL/fPHuv5i1Q26ac1fQwPzFvhg2vXvLYmkt/kgdBOqV6VwhDpBTDzZlymrKGbofOn8xEJ1UIQVxy2vSaFlmOpk2najCre+szIZ0oz0r3cYq77fVX6ykZBhZfvEkk=
  region: ap-northeast-2
  app: truenestweb
  env: truenestweb-env
after_deploy: npm start
env:
  global:
    secure: UVhOWIlY/Vu6ASLCTv6Nzp798gz6pK53Whl57fqz0lauJuMniZYN5WKx1ErEeD2P3edfJSgm7yU7I5Kliyfmpb4zR618Xh0k9DBXxPlWFgDqd6WUg0dYB0xl/ABBXlkTlUmN2aV6wzMfp9ZH1HRa9NyFxzhZt55/fkol9ceTpgvKKbbh+IXt42FWwilIharcD9dUUlLx7JTeKoAQr0j8VDY6y7XWauXKi3y/DOFv88GjBqzrk2RmZagowmILvuonwFVFj303TGQEIk8HGm3Nt8yQtDDWLESCF60UewrtEGaT62L9nDngeNkP2lUP6DPP3KCl3U8ujth5EG2x5TLJr+7a6Z+DA9qAGyZ+zAhDatx7zw9jrkKe8Hfwmtej/y5TGM/xCygV2OyZlu1/1Nrwlg7ryy9bUrILMQIly16Wm9IrPji5g1xNWGRP4d+/L+RXJddP6EgpgAK1KFHDCHO8zmrCHP+/uyFH7dZ587OQYDvRm7Q84JL1dLayPX4ngUNyqvGJxec9sPg1ZmliA+G0ReNjbQiQktIUOVPAVVOTqZ91M9DLL/fPHuv5i1Q26ac1fQwPzFvhg2vXvLYmkt/kgdBOqV6VwhDpBTDzZlymrKGbofOn8xEJ1UIQVxy2vSaFlmOpk2najCre+szIZ0oz0r3cYq77fVX6ykZBhZfvEkk=
