language: node_js
node_js:
  - '8'
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - npm rebuild node-sass --force
  - gulp
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: AKIAIU5T35CNLQZXZFMA
  secret_access_key:
    secure: uM1W0K55HwXTU/bcDAnCXCPU2zBmgqvAWCCmpVx7DSe6fFuR4ld23rwaY3e9xaAeaPgqKpbFnwRIqRlEc0F/2FddgTooQCZWNI075kJOvTfBuvxPxp2Nhx+PE+pwcj01Ob+PQXh6mK2ZcTO1cZYvFG5VewsIYUdtf8k6KTC9k/DRJaHoT4oAlZegZEXB/bBzIts3k5r9+rtaBC2KZQwIBS2VpJBO5pm8v3c74SaZneJse2Z9uXnlPvv/2WdftXjxUl+zKQ3AABskGB5ApHXn+jpqjycTbHVBLv4GN/PlYXMne3iYQp87uq6NiSw5APnPSuaL3kr+CFH+qtNHM/12nlmGhiZGVid6uNPinJ8QRiv2lAn3FmVF58PCRjOEqD9EX2laV0+p23iWjn8KtQkzuiGYluBIupNWRJvgHrFFlIWleft6rfF5UAu4qGVCixc479w+/N7/Ut8S77nbbT7/c5KaX6vCwjUfw6KNvH+LotH5engiO8dURtSs8btwq5UTHaMijXCQfsrQgapRXSmY4tCSvb0IFBVa2x//MVO3N/Qt1omTQ5U0rb56rNR7Ep1Nxnhf6SdVO5zBZcknqnd1Qb1vhHGf2KopA64PX3Kpt/7pMLNurt0Q+XF+9Ef3/zqRnCBe8gYM6G86H7YC8d6Pjv/9QQB1IcerHqR50xjXzBw=
  region: ap-northeast-2
  app: truenestweb
  env: truenestweb-env
  bucket_name: elasticbeanstalk-ap-northeast-2-748321859832
  on:
    repo: TrueNest/Web
    branch: master
